import type { ProductRequest } from "../types.js";
import { compileDomain } from "../domain.js";

function safeJson(value: string): string {
  return JSON.stringify(value);
}

export function generateWebProject(request: ProductRequest): Record<string, string> {
  const domain = compileDomain(request.idea);
  const title = request.idea.length > 72 ? `${request.idea.slice(0, 69)}...` : request.idea;
  const entities = domain.entities.map((item) => `<li>${item}</li>`).join("");
  const actions = domain.actions.map((item) => `<li>${item}</li>`).join("");
  const sections = domain.sections.map((item) => `<span className=\"pill\">${item}</span>`).join("");

  return {
    "generated/package.json": JSON.stringify({
      name: "generated-maestroarch-app",
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: { next: "^15.2.0", react: "^19.0.0", "react-dom": "^19.0.0" },
      devDependencies: { "@types/node": "^22.10.0", "@types/react": "^19.0.0", typescript: "^5.7.2" }
    }, null, 2) + "\n",
    "generated/tsconfig.json": JSON.stringify({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: false,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }]
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"]
    }, null, 2) + "\n",
    "generated/next-env.d.ts": "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n",
    "generated/app/layout.tsx": `import type { ReactNode } from "react";\nimport "./globals.css";\n\nexport const metadata = { title: ${safeJson(title)}, description: "Generated by MaestroArch" };\n\nexport default function RootLayout({ children }: { children: ReactNode }) {\n  return <html lang=\"es\"><body>{children}</body></html>;\n}\n`,
    "generated/app/page.tsx": `const idea = ${safeJson(request.idea)};\nconst domain = ${safeJson(domain.title)};\n\nexport default function Home() {\n  return (\n    <main className=\"shell\">\n      <section className=\"hero\">\n        <p className=\"eyebrow\">MaestroArch · MVP funcional de dominio</p>\n        <h1>{domain}</h1>\n        <p className=\"idea\">{idea}</p>\n        <div className=\"pills\">${sections}</div>\n      </section>\n      <section className=\"grid\">\n        <article className=\"card\"><h2>Entidades principales</h2><ul>${entities}</ul></article>\n        <article className=\"card\"><h2>Acciones P0</h2><ul>${actions}</ul></article>\n      </section>\n      <section className=\"card flow\">\n        <h2>Flujo principal</h2>\n        <p>El sistema ya tradujo la idea a una estructura de producto específica. El siguiente ciclo implementa persistencia e interacciones reales sobre estas entidades.</p>\n        <button type=\"button\">Empezar flujo principal</button>\n      </section>\n    </main>\n  );\n}\n`,
    "generated/app/globals.css": `*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#08111f;color:#f7f8fb}.shell{min-height:100vh;padding:40px 20px;max-width:1100px;margin:auto}.hero{padding:28px 0}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.14em;opacity:.7}.hero h1{font-size:clamp(34px,7vw,68px);line-height:1;margin:14px 0}.idea{max-width:800px;color:#c7d2e5;font-size:18px}.pills{display:flex;flex-wrap:wrap;gap:10px;margin-top:20px}.pill{padding:9px 12px;border:1px solid #32445f;border-radius:999px;background:#101b2e}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.card{background:#101b2e;border:1px solid #263752;border-radius:20px;padding:24px;box-shadow:0 18px 60px rgba(0,0,0,.22)}.card h2{margin-top:0}.card li{margin:10px 0}.flow{margin-top:18px}.flow button{border:0;border-radius:12px;padding:13px 18px;font-weight:700;cursor:pointer;background:white;color:#08111f}\n`,
    "generated/DOMAIN.json": JSON.stringify(domain, null, 2) + "\n",
    "generated/README.md": `# App generada por MaestroArch\n\n## Idea\n${request.idea}\n\n## Dominio detectado\n${domain.title} (${domain.kind})\n\n## Ejecutar\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Build\n\n\`\`\`bash\nnpm run build\n\`\`\`\n`
  };
}
