import type { ProductRequest } from "../types.js";

function safeJson(value: string): string {
  return JSON.stringify(value);
}

export function generateWebProject(request: ProductRequest): Record<string, string> {
  const title = request.idea.length > 72 ? `${request.idea.slice(0, 69)}...` : request.idea;
  return {
    "generated/package.json": JSON.stringify({
      name: "generated-maestroarch-app",
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start", lint: "next lint" },
      dependencies: { next: "^15.2.0", react: "^19.0.0", "react-dom": "^19.0.0" },
      devDependencies: { "@types/node": "^22.10.0", "@types/react": "^19.0.0", typescript: "^5.7.2" }
    }, null, 2) + "\n",
    "generated/tsconfig.json": JSON.stringify({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: false,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }]
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"]
    }, null, 2) + "\n",
    "generated/next-env.d.ts": "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n",
    "generated/app/layout.tsx": `import type { ReactNode } from "react";\nimport "./globals.css";\n\nexport const metadata = { title: ${safeJson(title)}, description: "Generated by MaestroArch" };\n\nexport default function RootLayout({ children }: { children: ReactNode }) {\n  return <html lang=\"es\"><body>{children}</body></html>;\n}\n`,
    "generated/app/page.tsx": `const idea = ${safeJson(request.idea)};\n\nexport default function Home() {\n  return (\n    <main className=\"shell\">\n      <section className=\"card\">\n        <p className=\"eyebrow\">MaestroArch · MVP generado</p>\n        <h1>{idea}</h1>\n        <p>Esta es la base ejecutable. El siguiente ciclo del orquestador debe convertir la especificación de dominio en el flujo funcional principal.</p>\n        <div className=\"status\">Estado: scaffold listo para implementación del dominio</div>\n      </section>\n    </main>\n  );\n}\n`,
    "generated/app/globals.css": `*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#0b1020;color:#f7f8fb}.shell{min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(760px,100%);background:#151c31;border:1px solid #2a3558;border-radius:24px;padding:32px;box-shadow:0 24px 70px rgba(0,0,0,.28)}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.14em;opacity:.72}h1{font-size:clamp(30px,6vw,58px);line-height:1.02;margin:16px 0}.status{margin-top:24px;padding:14px 16px;border-radius:14px;background:#0f1628;border:1px solid #34436f}\n`,
    "generated/README.md": `# App generada por MaestroArch\n\n## Idea\n${request.idea}\n\n## Ejecutar\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Build\n\n\`\`\`bash\nnpm run build\n\`\`\`\n`
  };
}
