import type { ProductRequest } from "../types.js";
import { compileDomain, type DomainSpec } from "../domain.js";

function safeJson(value: unknown): string {
  return JSON.stringify(value);
}

export function generateWebProject(request: ProductRequest, domain: DomainSpec = compileDomain(request.idea)): Record<string, string> {
  const title = request.idea.length > 72 ? `${request.idea.slice(0, 69)}...` : request.idea;

  return {
    "generated/package.json": JSON.stringify({
      name: "generated-maestroarch-app",
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: { next: "^15.2.0", react: "^19.0.0", "react-dom": "^19.0.0" },
      devDependencies: { "@types/node": "^22.10.0", "@types/react": "^19.0.0", typescript: "^5.7.2" }
    }, null, 2) + "\n",
    "generated/tsconfig.json": JSON.stringify({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: false,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }]
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"]
    }, null, 2) + "\n",
    "generated/next-env.d.ts": "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n",
    "generated/app/layout.tsx": `import type { ReactNode } from "react";\nimport "./globals.css";\n\nexport const metadata = { title: ${safeJson(title)}, description: "Generated by MaestroArch" };\n\nexport default function RootLayout({ children }: { children: ReactNode }) {\n  return <html lang=\"es\"><body>{children}</body></html>;\n}\n`,
    "generated/app/page.tsx": `"use client";\n\nimport { FormEvent, useEffect, useState } from "react";\n\ntype RecordItem = { id: string; name: string; detail: string; status: string };\n\nconst idea = ${safeJson(request.idea)};\nconst domain = ${safeJson(domain.title)};\nconst kind = ${safeJson(domain.kind)};\nconst entities = ${safeJson(domain.entities)} as string[];\nconst actions = ${safeJson(domain.actions)} as string[];\nconst sections = ${safeJson(domain.sections)} as string[];\nconst storageKey = \"maestroarch:\" + kind + \":records\";\n\nexport default function Home() {\n  const [records, setRecords] = useState<RecordItem[]>([]);\n  const [name, setName] = useState(\"\");\n  const [detail, setDetail] = useState(\"\");\n\n  useEffect(() => {\n    try {\n      const saved = localStorage.getItem(storageKey);\n      if (saved) setRecords(JSON.parse(saved));\n    } catch {}\n  }, []);\n\n  useEffect(() => {\n    localStorage.setItem(storageKey, JSON.stringify(records));\n  }, [records]);\n\n  function addRecord(event: FormEvent) {\n    event.preventDefault();\n    if (!name.trim()) return;\n    setRecords((current) => [{ id: crypto.randomUUID(), name: name.trim(), detail: detail.trim(), status: \"nuevo\" }, ...current]);\n    setName(\"\");\n    setDetail(\"\");\n  }\n\n  function advance(id: string) {\n    setRecords((current) => current.map((item) => item.id === id ? { ...item, status: item.status === \"nuevo\" ? \"en curso\" : \"completado\" } : item));\n  }\n\n  function remove(id: string) {\n    setRecords((current) => current.filter((item) => item.id !== id));\n  }\n\n  return (\n    <main className=\"shell\">\n      <section className=\"hero\">\n        <p className=\"eyebrow\">MaestroArch · MVP generado</p>\n        <h1>{domain}</h1>\n        <p className=\"idea\">{idea}</p>\n        <div className=\"pills\">{sections.map((item) => <span className=\"pill\" key={item}>{item}</span>)}</div>\n      </section>\n\n      <section className=\"grid\">\n        <article className=\"card\">\n          <h2>Crear {entities[1] ?? entities[0]}</h2>\n          <form onSubmit={addRecord} className=\"form\">\n            <label>Nombre<input value={name} onChange={(e) => setName(e.target.value)} placeholder={entities[0] ?? \"Registro\"} /></label>\n            <label>Detalle<input value={detail} onChange={(e) => setDetail(e.target.value)} placeholder={actions[0] ?? \"Detalle\"} /></label>\n            <button type=\"submit\">{actions[0] ?? \"Crear\"}</button>\n          </form>\n        </article>\n\n        <article className=\"card\">\n          <h2>Modelo del dominio</h2>\n          <ul>{entities.map((item) => <li key={item}>{item}</li>)}</ul>\n        </article>\n      </section>\n\n      <section className=\"card flow\">\n        <div className=\"flowHeader\"><div><p className=\"eyebrow\">Flujo principal</p><h2>Actividad</h2></div><strong>{records.length} registros</strong></div>\n        {records.length === 0 ? <p className=\"empty\">Todavía no hay actividad. Creá el primer registro para probar el flujo.</p> : (\n          <div className=\"records\">{records.map((item) => (\n            <article className=\"record\" key={item.id}>\n              <div><strong>{item.name}</strong><p>{item.detail || \"Sin detalle\"}</p><span className=\"status\">{item.status}</span></div>\n              <div className=\"recordActions\"><button onClick={() => advance(item.id)}>{item.status === \"nuevo\" ? (actions[1] ?? \"Avanzar\") : \"Completar\"}</button><button className=\"ghost\" onClick={() => remove(item.id)}>Eliminar</button></div>\n            </article>\n          ))}</div>\n        )}\n      </section>\n    </main>\n  );\n}\n`,
    "generated/app/globals.css": `*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#08111f;color:#f7f8fb}.shell{min-height:100vh;padding:40px 20px;max-width:1100px;margin:auto}.hero{padding:28px 0}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.14em;opacity:.7;margin:0}.hero h1{font-size:clamp(34px,7vw,68px);line-height:1;margin:14px 0}.idea{max-width:800px;color:#c7d2e5;font-size:18px}.pills{display:flex;flex-wrap:wrap;gap:10px;margin-top:20px}.pill,.status{padding:8px 11px;border:1px solid #32445f;border-radius:999px;background:#101b2e;font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:18px}.card{background:#101b2e;border:1px solid #263752;border-radius:20px;padding:24px;box-shadow:0 18px 60px rgba(0,0,0,.22)}.card h2{margin-top:8px}.card li{margin:10px 0}.form{display:grid;gap:14px}.form label{display:grid;gap:7px;font-size:13px;color:#c7d2e5}.form input{width:100%;padding:12px 14px;border-radius:12px;border:1px solid #32445f;background:#08111f;color:white}.form button,.recordActions button{border:0;border-radius:12px;padding:12px 16px;font-weight:700;cursor:pointer;background:white;color:#08111f}.flow{margin-top:18px}.flowHeader{display:flex;align-items:center;justify-content:space-between;gap:20px}.empty{padding:24px 0;color:#9fb0c9}.records{display:grid;gap:12px}.record{display:flex;justify-content:space-between;gap:20px;padding:16px;border-radius:14px;background:#0b1526;border:1px solid #263752}.record p{margin:6px 0 12px;color:#b9c5d8}.recordActions{display:flex;gap:8px;align-items:center}.recordActions .ghost{background:transparent;color:#dbe4f2;border:1px solid #32445f}@media(max-width:640px){.record{flex-direction:column}.recordActions{align-items:stretch}.recordActions button{flex:1}.flowHeader{align-items:flex-start;flex-direction:column}}\n`,
    "generated/DOMAIN.json": JSON.stringify(domain, null, 2) + "\n",
    "generated/README.md": `# App generada por MaestroArch\n\n## Idea\n${request.idea}\n\n## Dominio detectado\n${domain.title} (${domain.kind})\n\n## Qué funciona\n- creación de registros del dominio;\n- avance de estado;\n- eliminación;\n- persistencia local en el navegador;\n- interfaz responsive;\n- build de Next.js.\n\n## Ejecutar\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Build\n\n\`\`\`bash\nnpm run build\n\`\`\`\n`
  };
}
